#!/bin/bash

# Instructions to configure Info.plist for Quote AI app

echo "================================"
echo "Info.plist Configuration Steps"
echo "================================"
echo ""
echo "The Info.plist file has been created at:"
echo "/Users/linfanbin/Desktop/Quote AI/Quote AI/Quote AI/Info.plist"
echo ""
echo "You need to add this file to your Xcode project. Follow these steps:"
echo ""
echo "1. Open Xcode with your Quote AI project"
echo "2. In the Project Navigator (left sidebar), RIGHT-CLICK on the 'Quote AI' folder (the yellow one)"
echo "3. Select 'Add Files to \"Quote AI\"...'"
echo "4. Navigate to and select: Quote AI/Quote AI/Info.plist"
echo "5. Make sure 'Copy items if needed' is UNCHECKED"
echo "6. Make sure 'Add to targets: Quote AI' is CHECKED"
echo "7. Click 'Add'"
echo ""
echo "8. Click on the Quote AI project (blue icon) in the navigator"
echo "9. Select the 'Quote AI' target"
echo "10. Go to the 'Build Settings' tab"
echo "11. Search for 'Generate Info.plist File'"
echo "12. Change it from 'Yes' to 'No'"
echo "13. Search for 'Info.plist File'"
echo "14. Set it to: Quote AI/Info.plist"
echo ""
echo "15. Clean build folder (Product → Clean Build Folder or Cmd+Shift+K)"
echo "16. Build and run (Cmd+R)"
echo ""
echo "================================"
echo ""
